sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - cd $TRAVIS_BUILD_DIR/source
  - npm install

script:
  - ng test --karma-config $TRAVIS_BUILD_DIR/source/src/karma.headless.conf.js
  - ng e2e --protractor-config $TRAVIS_BUILD_DIR/source/e2e/protractor.headless.conf.js
