sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "8"

branches:
  only:
    - master

cache:
  directories:
    - ./node_modules

install:
  - npm install -g @angular/cli

before_script:
  - cd $TRAVIS_BUILD_DIR/source
  - npm install
  - npm build

script:
  - ng test --watch=false --progress=false --browsers=ChromeHeadlessCI
#  - ng e2e --protractor-config=$TRAVIS_BUILD_DIR/source/e2e/protractor.ci.conf.js
