version: 2
jobs:
  build:
    working_directory: ~/project/source
    docker:
      - image: circleci/node:11-browsers
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          key: node-modules-cache-{{ checksum "package-lock.json" }}
#      - run:
#          name: Install angular-cli
#          command: npm install -g angular-cli
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: node-modules-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: ng build
      - run:
          name: unit test
          command: ng test --watch=false --progress=false --browsers=ChromeHeadlessCI
      - run:
          name: e2e test
          command: ng e2e --protractor-config=./e2e/protractor.ci.conf.js
