name: build-checks

on:
  pull_request:
    branches:
      - master

jobs:
  build-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - run: |
          npm ci
          ./node_modules/.bin/ng test --watch=false --progress=false --browsers=ChromeHeadlessCI
